import { createWorker } from 'tesseract.js';
import { DEFAULT_BANK_ACCOUNTS, normalizeAccount, normalizeReference } from '../config/subscriptionBanks';
const upper=(v='')=>String(v||'').replace(/\s+/g,' ').trim().toUpperCase();
const number=(v='')=>Number(String(v||'').replace(/,/g,''));
export async function sha256File(file){const b=await file.arrayBuffer();const d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function detectBank(text=''){const s=upper(text);if(s.includes('MALDIVES ISLAMIC BANK')||/\bMIB\b/.test(s))return'MIB';if(s.includes('BANK OF MALDIVES')||/\bBLAZ[A-Z0-9]+\b/.test(s))return'BML';return'';}
export function extractReference(text='',bankId=''){const s=upper(text);if(bankId==='BML'){const m=s.match(/\bBLAZ[A-Z0-9]{6,}\b/);return normalizeReference(m?.[0]||'');}const m=s.match(/(?:REFERENCE\s*#?|REF(?:ERENCE)?\s*NO\.?)\s*[:#-]?\s*([A-Z0-9-]{5,})/);return normalizeReference(m?.[1]||'');}
export function extractAmount(text=''){const s=String(text||'');const patterns=[/(?:AMOUNT|TRANSFER(?:RED)?|TOTAL)\s*[:\-]?\s*(?:MVR\s*)?([0-9,]+\.[0-9]{2})/i,/(?:MVR)\s*([0-9,]+\.[0-9]{2})/i,/([0-9,]+\.[0-9]{2})\s*MVR/i];for(const r of patterns){const m=s.match(r);if(m)return number(m[1]);}const vals=[...s.matchAll(/(?:MVR\s*)?([0-9]{1,3}(?:,[0-9]{3})*(?:\.[0-9]{2})|[0-9]+\.[0-9]{2})\s*(?:MVR)?/gi)].map(m=>number(m[1])).filter(x=>Number.isFinite(x)&&x>0);return vals.length?Math.max(...vals):0;}
export function extractDestinationAccount(text='',bankId=''){const s=upper(text).replace(/\s/g,'');if(bankId==='BML'){const expected=DEFAULT_BANK_ACCOUNTS.BML.accountNumber;return s.includes(expected)?expected:'';}return'';}
export function evaluateReceipt({text,bankId,expectedBank,expectedAmount,configuredAccount,amount,reference,destinationAccount}){const reasons=[],warnings=[],s=upper(text);if(!bankId)reasons.push('Bank could not be identified.');if(expectedBank&&bankId&&expectedBank!==bankId)reasons.push('Uploaded slip is for a different bank.');if(!reference)reasons.push('Transaction reference could not be detected.');if(!amount)reasons.push('Transferred amount could not be detected.');if(expectedAmount>0&&amount>0&&Math.abs(amount-expectedAmount)>0.01)reasons.push('Transferred amount does not match the subscription amount.');if(bankId==='BML'){const exp=normalizeAccount(configuredAccount?.accountNumber);if(exp&&normalizeAccount(destinationAccount)!==exp)reasons.push('BML destination account does not match the configured subscription account.');}if(bankId==='MIB'){if(!s.includes('MALDIVES ISLAMIC BANK')&&!/\bMIB\b/.test(s))reasons.push('MIB branding could not be confirmed.');if(!s.includes(upper(configuredAccount?.accountName||'ALI JAILAM')))warnings.push('Destination account name was not confidently detected.');warnings.push('The supplied MIB slip format does not show the destination account number; Super Admin must verify the account manually.');}return{automaticallyRejected:reasons.length>0,reasons,warnings,riskLevel:reasons.length?'REJECT':warnings.length?'REVIEW':'LOW'};}
export async function analyzeReceiptImage(file,{expectedBank='',expectedAmount=0,bankAccounts=DEFAULT_BANK_ACCOUNTS,onProgress=()=>{}}={}){if(!file)throw new Error('Upload a transfer slip image.');if(!file.type.startsWith('image/'))throw new Error('Slip must be an image.');if(file.size>8*1024*1024)throw new Error('Slip image must be smaller than 8 MB.');const fileHash=await sha256File(file);const worker=await createWorker('eng',1,{logger:m=>{if(m?.status==='recognizing text')onProgress(Math.round((m.progress||0)*100));}});let result;try{result=await worker.recognize(file);}finally{await worker.terminate();}const text=result?.data?.text||'',confidence=Number(result?.data?.confidence||0),bankId=detectBank(text),amount=extractAmount(text),reference=extractReference(text,bankId),destinationAccount=extractDestinationAccount(text,bankId),configuredAccount=bankAccounts[bankId]||DEFAULT_BANK_ACCOUNTS[bankId]||{};const validation=evaluateReceipt({text,bankId,expectedBank,expectedAmount,configuredAccount,amount,reference,destinationAccount});if(confidence<45){validation.warnings.push('OCR confidence is low; manual verification is recommended.');if(!validation.automaticallyRejected)validation.riskLevel='REVIEW';}return{bankId,text:String(text).replace(/\s+/g,' ').trim(),ocrConfidence:confidence,amount,reference,destinationAccount,fileHash,...validation};}
