import { useMemo, useState } from 'react';
import Modal from '../components/Modal';
import EmptyState from '../components/EmptyState';
import { deleteRecord, saveRecord } from '../services/database';
import { currency, safeNumber } from '../utils/format';

const blank = { assetNumber: '', name: '', category: 'Equipment', purchaseDate: '', purchaseCost: 0, location: 'Main Location', condition: 'GOOD', status: 'ACTIVE', assignedEmployeeId: '', serialNumber: '', nextMaintenanceDate: '', notes: '' };
const CONDITIONS = ['NEW', 'GOOD', 'FAIR', 'NEEDS SERVICE', 'DAMAGED'];

export default function Assets({ assets = [], employees = [], settings = {}, notify = () => {} }) {
  const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank); const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL');
  const employeeName = (id) => employees.find((x)=>x.id===id)?.name || 'Unassigned';
  const filtered = useMemo(()=>assets.filter((row)=>{const q=search.trim().toLowerCase();return(!q||`${row.name||''} ${row.assetNumber||''} ${row.serialNumber||''} ${row.category||''}`.toLowerCase().includes(q))&&(status==='ALL'||row.status===status);}),[assets,search,status]);
  const open=(record=null)=>{setEditing(record||{});setForm({...blank,...(record||{})});};
  const save=async()=>{if(!form.name.trim())return notify('Asset name is required.','error');await saveRecord('assets',{...form,name:form.name.trim(),assetNumber:form.assetNumber.trim()||`AST-${String(Date.now()).slice(-7)}`,serialNumber:form.serialNumber.trim(),location:form.location.trim()||'Main Location',purchaseCost:safeNumber(form.purchaseCost),notes:form.notes.trim(),assignedEmployeeName:employeeName(form.assignedEmployeeId)},editing?.id||null);setEditing(null);notify('Company asset saved.');};
  const maintenanceDue=assets.filter(x=>x.nextMaintenanceDate&&new Date(x.nextMaintenanceDate)<=new Date(Date.now()+30*86400000)&&x.status!=='RETIRED').length;
  return <div className="v5-page"><section className="v5-hero panel"><div><p className="eyebrow">COMPANY PROPERTY</p><h2>Asset Register</h2><p>Track equipment, vehicles, uniforms and other company property with assignments and maintenance dates.</p></div><button className="button button-primary" onClick={()=>open()}>＋ Add asset</button></section>
  <section className="v5-kpi-grid"><article className="panel"><span>Assets</span><strong>{assets.length}</strong><small>registered items</small></article><article className="panel"><span>Purchase value</span><strong>{currency(assets.reduce((s,x)=>s+safeNumber(x.purchaseCost),0),settings.currency)}</strong><small>recorded cost</small></article><article className="panel"><span>Maintenance due</span><strong>{maintenanceDue}</strong><small>within 30 days / overdue</small></article></section>
  <section className="panel v5-toolbar"><div className="search-box">⌕<input placeholder="Search asset, number, serial or category" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option>ACTIVE</option><option>IN REPAIR</option><option>RETIRED</option><option>LOST</option></select></section>
  <section className="v5-card-grid">{filtered.map(row=><article className="panel v5-data-card" key={row.id}><header><div className="v5-avatar">◇</div><div><h3>{row.name}</h3><p>{row.assetNumber} · {row.category}</p></div><span className="v5-pill">{row.status||'ACTIVE'}</span></header><div className="v5-detail-list"><span>Condition <b>{row.condition||'GOOD'}</b></span><span>Location <b>{row.location||'Main Location'}</b></span><span>Assigned <b>{employeeName(row.assignedEmployeeId)}</b></span><span>Maintenance <b>{row.nextMaintenanceDate||'—'}</b></span></div><footer className="row-actions"><button onClick={()=>open(row)}>Edit</button><button className="danger" onClick={async()=>{if(confirm(`Delete ${row.name}?`)){await deleteRecord('assets',row.id);notify('Asset deleted.');}}}>Delete</button></footer></article>)}</section>
  {!filtered.length&&<section className="panel"><EmptyState icon="◇" title="No assets found" text="Add vehicles, equipment, uniforms or other company property."/></section>}
  <Modal open={Boolean(editing)} title={editing?.id?'Edit asset':'Add asset'} onClose={()=>setEditing(null)}><div className="form-grid"><label className="wide"><span>Asset name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Asset number</span><input placeholder="Auto if empty" value={form.assetNumber} onChange={e=>setForm({...form,assetNumber:e.target.value})}/></label><label><span>Category</span><input placeholder="Vehicle, equipment, uniform..." value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label><span>Serial / plate number</span><input value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})}/></label><label><span>Location</span><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label><span>Purchase date</span><input type="date" value={form.purchaseDate} onChange={e=>setForm({...form,purchaseDate:e.target.value})}/></label><label><span>Purchase cost</span><input type="number" min="0" step="0.01" value={form.purchaseCost} onChange={e=>setForm({...form,purchaseCost:e.target.value})}/></label><label><span>Condition</span><select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}>{CONDITIONS.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>IN REPAIR</option><option>RETIRED</option><option>LOST</option></select></label><label><span>Assigned employee</span><select value={form.assignedEmployeeId} onChange={e=>setForm({...form,assignedEmployeeId:e.target.value})}><option value="">Unassigned</option>{employees.filter(x=>x.active!==false).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label><span>Next maintenance</span><input type="date" value={form.nextMaintenanceDate} onChange={e=>setForm({...form,nextMaintenanceDate:e.target.value})}/></label><label className="wide"><span>Notes</span><textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><footer className="modal-actions"><button className="button button-ghost" onClick={()=>setEditing(null)}>Cancel</button><button className="button button-primary" onClick={save}>Save asset</button></footer></Modal>
  </div>;
}
