import { useMemo, useRef, useState } from 'react';
import Modal from '../components/Modal';
import EmptyState from '../components/EmptyState';
import { deleteRecord, saveRecord } from '../services/database';
import { fulfillMarketplaceOrderV5 } from '../services/commerce';
import { currency, safeNumber } from '../utils/format';

const channelBlank = { name: '', type: 'Marketplace', active: true, notes: '' };
const orderBlank = { channelId: '', orderNumber: '', customerName: '', customerEmail: '', paymentStatus: 'PAID', status: 'NEW', shippingMethod: '', total: 0 };
const newLine = () => ({ productId: '', quantity: 1, unitPrice: 0 });

const parseCsv = (text) => {
  const rows = String(text || '').trim().split(/\r?\n/).filter(Boolean);
  if (rows.length < 2) return [];
  const headers = rows[0].split(',').map((h) => h.trim());
  return rows.slice(1).map((line) => {
    const values = line.split(',').map((value) => value.trim());
    return Object.fromEntries(headers.map((header, index) => [header, values[index] || '']));
  });
};

export default function Marketplace({
  channels = [], orders = [], products = [], customers = [], settings = {}, notify = () => {},
}) {
  const [channelEditor, setChannelEditor] = useState(null); const [channelForm, setChannelForm] = useState(channelBlank);
  const [orderEditor, setOrderEditor] = useState(null); const [orderForm, setOrderForm] = useState(orderBlank); const [lines, setLines] = useState([newLine()]);
  const [statusFilter, setStatusFilter] = useState('ALL'); const [channelFilter, setChannelFilter] = useState('ALL'); const fileRef = useRef(null);
  const filtered = useMemo(()=>orders.filter(o=>(statusFilter==='ALL'||String(o.status).toUpperCase()===statusFilter)&&(channelFilter==='ALL'||o.channelId===channelFilter)),[orders,statusFilter,channelFilter]);
  const channelName=(id)=>channels.find(x=>x.id===id)?.name||'Marketplace';
  const openChannel=(record=null)=>{setChannelEditor(record||{});setChannelForm({...channelBlank,...(record||{})});};
  const saveChannel=async()=>{if(!channelForm.name.trim())return notify('Channel name is required.','error');await saveRecord('salesChannels',{...channelForm,name:channelForm.name.trim()},channelEditor?.id||null);setChannelEditor(null);notify('Sales channel saved.');};
  const openOrder=(record=null)=>{setOrderEditor(record||{});setOrderForm({...orderBlank,...(record||{})});setLines(record?.items?.length?record.items.map(x=>({...x})):[newLine()]);};
  const lineTotal=(line)=>safeNumber(line.quantity)*safeNumber(line.unitPrice); const orderTotal=lines.reduce((s,x)=>s+lineTotal(x),0);
  const saveOrder=async()=>{if(!orderForm.channelId)return notify('Select a sales channel.','error');const items=lines.filter(x=>x.productId&&safeNumber(x.quantity)>0).map(x=>{const p=products.find(y=>y.id===x.productId);return{productId:x.productId,name:p?.name||'Item',sku:p?.sku||'',quantity:safeNumber(x.quantity),unitPrice:safeNumber(x.unitPrice||p?.price),amount:lineTotal(x)};});if(!items.length)return notify('Add at least one inventory item.','error');const channel=channels.find(x=>x.id===orderForm.channelId);await saveRecord('marketplaceOrders',{...orderForm,channelName:channel?.name||'Marketplace',orderNumber:orderForm.orderNumber.trim()||`WEB-${String(Date.now()).slice(-8)}`,items,total:safeNumber(orderForm.total)||items.reduce((s,x)=>s+safeNumber(x.amount),0),status:orderForm.status||'NEW',createdDate:orderEditor?.createdDate||new Date().toISOString().slice(0,10)},orderEditor?.id||null);setOrderEditor(null);notify('Marketplace order saved.');};
  const fulfill=async(order)=>{if(!confirm(`Fulfill ${order.orderNumber}? Stock will be deducted.`))return;try{await fulfillMarketplaceOrderV5(order.id);notify('Marketplace order fulfilled and inventory updated.');}catch(e){notify(e.message||'Could not fulfill order.','error');}};
  const importCsv=async(file)=>{if(!file)return;const rows=parseCsv(await file.text());let imported=0;for(const row of rows){const product=products.find(p=>String(p.sku||'').toLowerCase()===String(row.sku||'').toLowerCase());if(!product)continue;let channel=channels.find(c=>String(c.name||'').toLowerCase()===String(row.channel||'').toLowerCase());if(!channel){const id=await saveRecord('salesChannels',{name:row.channel||'Imported channel',type:'Marketplace',active:true});channel={id,name:row.channel||'Imported channel'};}const quantity=Math.max(1,safeNumber(row.quantity));await saveRecord('marketplaceOrders',{channelId:channel.id,channelName:channel.name,orderNumber:row.orderNumber||`WEB-${String(Date.now()).slice(-8)}-${imported}`,customerName:row.customerName||'Online Customer',customerEmail:row.customerEmail||'',paymentStatus:row.paymentStatus||'PAID',status:'NEW',items:[{productId:product.id,name:product.name,sku:product.sku||'',quantity,unitPrice:safeNumber(row.unitPrice||product.price),amount:quantity*safeNumber(row.unitPrice||product.price)}],total:safeNumber(row.total)||quantity*safeNumber(row.unitPrice||product.price),createdDate:new Date().toISOString().slice(0,10)});imported+=1;}notify(imported?`${imported} marketplace order(s) imported.`:'No rows matched a product SKU.',imported?'success':'error');fileRef.current.value='';};
  return <div className="v5-page"><section className="v5-hero panel"><div><p className="eyebrow">OMNICHANNEL SALES</p><h2>Marketplace order hub</h2><p>Bring orders from social selling, marketplace apps and online stores into the same stock and sales workflow.</p></div><div className="v5-action-row"><button className="button button-ghost" onClick={()=>openChannel()}>＋ Channel</button><button className="button button-primary" onClick={()=>openOrder()}>＋ Order</button></div></section>
  <section className="v5-kpi-grid"><article className="panel"><span>Channels</span><strong>{channels.filter(x=>x.active!==false).length}</strong><small>active sales sources</small></article><article className="panel"><span>New orders</span><strong>{orders.filter(x=>String(x.status).toUpperCase()==='NEW').length}</strong><small>awaiting fulfillment</small></article><article className="panel"><span>Fulfilled sales</span><strong>{currency(orders.filter(x=>String(x.status).toUpperCase()==='FULFILLED').reduce((s,x)=>s+safeNumber(x.total),0),settings.currency)}</strong><small>marketplace revenue</small></article></section>
  <section className="panel v5-toolbar"><select value={channelFilter} onChange={e=>setChannelFilter(e.target.value)}><option value="ALL">All channels</option>{channels.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All statuses</option><option value="NEW">New</option><option value="PROCESSING">Processing</option><option value="FULFILLED">Fulfilled</option><option value="CANCELLED">Cancelled</option></select><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={e=>importCsv(e.target.files?.[0])}/><small>CSV columns: orderNumber, channel, customerName, customerEmail, sku, quantity, unitPrice, total</small></section>
  <section className="v5-table-wrap panel"><table><thead><tr><th>Order</th><th>Channel</th><th>Customer</th><th>Items</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>{filtered.map(order=><tr key={order.id}><td><b>{order.orderNumber}</b></td><td>{order.channelName||channelName(order.channelId)}</td><td>{order.customerName||'Online Customer'}</td><td>{(order.items||[]).reduce((s,x)=>s+safeNumber(x.quantity),0)}</td><td><span className="v5-pill">{order.status||'NEW'}</span></td><td>{currency(order.total,settings.currency)}</td><td><div className="row-actions"><button onClick={()=>openOrder(order)}>Edit</button>{!['FULFILLED','CANCELLED'].includes(String(order.status).toUpperCase())&&<button onClick={()=>fulfill(order)}>Fulfill</button>}<button className="danger" onClick={async()=>{if(confirm(`Delete ${order.orderNumber}?`)){await deleteRecord('marketplaceOrders',order.id);notify('Marketplace order deleted.');}}}>Delete</button></div></td></tr>)}</tbody></table></section>
  {!filtered.length&&<section className="panel"><EmptyState icon="◎" title="No marketplace orders" text="Add an order manually or import a CSV from an online sales channel."/></section>}
  <section className="v5-channel-grid">{channels.map(ch=><article className="panel v5-channel-card" key={ch.id}><div><span className="v5-avatar">{ch.name.slice(0,2).toUpperCase()}</span><h3>{ch.name}</h3><p>{ch.type||'Marketplace'}</p></div><div className="row-actions"><button onClick={()=>openChannel(ch)}>Edit</button><button className="danger" onClick={async()=>{if(confirm(`Delete ${ch.name}?`)){await deleteRecord('salesChannels',ch.id);notify('Channel deleted.');}}}>Delete</button></div></article>)}</section>
  <Modal open={Boolean(channelEditor)} title={channelEditor?.id?'Edit sales channel':'Add sales channel'} onClose={()=>setChannelEditor(null)}><div className="form-grid"><label className="wide"><span>Channel name</span><input placeholder="Facebook, Instagram, Shopify, website…" value={channelForm.name} onChange={e=>setChannelForm({...channelForm,name:e.target.value})}/></label><label><span>Channel type</span><select value={channelForm.type} onChange={e=>setChannelForm({...channelForm,type:e.target.value})}><option>Marketplace</option><option>Social</option><option>Web Store</option><option>Delivery App</option><option>Other</option></select></label><label className="checkbox-label"><input type="checkbox" checked={Boolean(channelForm.active)} onChange={e=>setChannelForm({...channelForm,active:e.target.checked})}/><span>Active</span></label><label className="wide"><span>Notes</span><textarea rows="3" value={channelForm.notes} onChange={e=>setChannelForm({...channelForm,notes:e.target.value})}/></label></div><footer className="modal-actions"><button className="button button-ghost" onClick={()=>setChannelEditor(null)}>Cancel</button><button className="button button-primary" onClick={saveChannel}>Save channel</button></footer></Modal>
  <Modal open={Boolean(orderEditor)} title={orderEditor?.id?'Edit marketplace order':'Add marketplace order'} onClose={()=>setOrderEditor(null)}><div className="form-grid"><label><span>Channel</span><select value={orderForm.channelId} onChange={e=>setOrderForm({...orderForm,channelId:e.target.value})}><option value="">Select channel</option>{channels.filter(x=>x.active!==false).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Order number</span><input value={orderForm.orderNumber} onChange={e=>setOrderForm({...orderForm,orderNumber:e.target.value})}/></label><label><span>Customer name</span><input value={orderForm.customerName} onChange={e=>setOrderForm({...orderForm,customerName:e.target.value})}/></label><label><span>Customer email</span><input type="email" value={orderForm.customerEmail} onChange={e=>setOrderForm({...orderForm,customerEmail:e.target.value})}/></label><label><span>Payment</span><select value={orderForm.paymentStatus} onChange={e=>setOrderForm({...orderForm,paymentStatus:e.target.value})}><option>PAID</option><option>UNPAID</option><option>COD</option></select></label><label><span>Status</span><select value={orderForm.status} onChange={e=>setOrderForm({...orderForm,status:e.target.value})}><option>NEW</option><option>PROCESSING</option><option>CANCELLED</option></select></label></div><div className="v5-line-editor"><header><h4>Order items</h4><button className="button button-ghost" onClick={()=>setLines([...lines,newLine()])}>＋ Add item</button></header>{lines.map((line,i)=>{const p=products.find(x=>x.id===line.productId);return <div className="v5-line-row" key={i}><select value={line.productId} onChange={e=>{const product=products.find(x=>x.id===e.target.value);setLines(lines.map((x,index)=>index===i?{...x,productId:e.target.value,unitPrice:safeNumber(product?.price)}:x));}}><option value="">Select inventory item</option>{products.filter(x=>x.itemType!=='service').map(x=><option key={x.id} value={x.id}>{x.name}{x.sku?` · ${x.sku}`:''}</option>)}</select><input type="number" min="1" value={line.quantity} onChange={e=>setLines(lines.map((x,index)=>index===i?{...x,quantity:e.target.value}:x))}/><input type="number" min="0" step="0.01" value={line.unitPrice||p?.price||0} onChange={e=>setLines(lines.map((x,index)=>index===i?{...x,unitPrice:e.target.value}:x))}/><button className="button button-ghost" onClick={()=>setLines(lines.filter((_,index)=>index!==i))}>×</button></div>;})}</div><div className="v5-total-strip"><span>Items total</span><strong>{currency(orderTotal,settings.currency)}</strong></div><footer className="modal-actions"><button className="button button-ghost" onClick={()=>setOrderEditor(null)}>Cancel</button><button className="button button-primary" onClick={saveOrder}>Save order</button></footer></Modal>
  </div>;
}
