import { useMemo, useState } from 'react';
import Modal from '../components/Modal';
import EmptyState from '../components/EmptyState';
import { deleteRecord, saveRecord } from '../services/database';
import { receivePurchaseOrderV5 } from '../services/commerce';
import { currency, safeNumber } from '../utils/format';

const blank = { supplierId: '', expectedDate: '', notes: '', status: 'ORDERED' };
const newLine = () => ({ productId: '', orderedQty: 1, unitCost: 0, receivedQty: 0 });

export default function PurchaseOrders({ purchaseOrders = [], suppliers = [], products = [], settings = {}, notify = () => {} }) {
  const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank); const [lines, setLines] = useState([newLine()]);
  const [receiving, setReceiving] = useState(null); const [receipt, setReceipt] = useState([]); const [receiveNote, setReceiveNote] = useState('');
  const supplierName = (id) => suppliers.find((x)=>x.id===id)?.name || 'Unknown supplier';
  const total = (items=[]) => items.reduce((s,x)=>s+safeNumber(x.orderedQty)*safeNumber(x.unitCost),0);
  const ordered = useMemo(()=>purchaseOrders.filter((po)=>String(po.status||'').toUpperCase()!=='CANCELLED'),[purchaseOrders]);
  const open = (po=null) => { setEditing(po||{}); setForm({ ...blank, ...(po||{}) }); setLines(po?.items?.length ? po.items.map((x)=>({...x})) : [newLine()]); };
  const updateLine=(i,key,value)=>setLines((cur)=>cur.map((row,index)=>index===i?{...row,[key]:value}:row));
  const save=async()=>{ if(!form.supplierId) return notify('Select a supplier.','error'); const items=lines.filter(x=>x.productId&&safeNumber(x.orderedQty)>0).map(x=>{const p=products.find(y=>y.id===x.productId);return{productId:x.productId,name:p?.name||'Item',sku:p?.sku||'',orderedQty:safeNumber(x.orderedQty),receivedQty:safeNumber(x.receivedQty),unitCost:safeNumber(x.unitCost||p?.cost)};}); if(!items.length)return notify('Add at least one item.','error'); const poNumber=editing?.poNumber||`PO-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-4)}`; await saveRecord('purchaseOrders',{...form,poNumber,items,total:total(items),status:form.status||'ORDERED',orderDate:editing?.orderDate||new Date().toISOString().slice(0,10)},editing?.id||null);setEditing(null);notify('Purchase order saved.');};
  const openReceive=(po)=>{setReceiving(po);setReceipt((po.items||[]).map(x=>({productId:x.productId,name:x.name,quantity:Math.max(0,safeNumber(x.orderedQty)-safeNumber(x.receivedQty))})));setReceiveNote('');};
  const receive=async()=>{try{await receivePurchaseOrderV5(receiving.id,receipt.map(x=>({productId:x.productId,quantity:safeNumber(x.quantity)})).filter(x=>x.quantity>0),receiveNote);notify('Stock received and inventory updated.');setReceiving(null);}catch(e){notify(e.message||'Could not receive order.','error');}};
  return <div className="v5-page"><section className="v5-hero panel"><div><p className="eyebrow">PROCUREMENT</p><h2>Purchase orders</h2><p>Order stock from suppliers, receive partial shipments and keep inventory synchronized.</p></div><button className="button button-primary" onClick={()=>open()}>＋ New purchase order</button></section>
  <section className="v5-kpi-grid"><article className="panel"><span>Open POs</span><strong>{ordered.filter(x=>['ORDERED','PARTIAL','DRAFT'].includes(String(x.status).toUpperCase())).length}</strong><small>awaiting stock</small></article><article className="panel"><span>Received</span><strong>{ordered.filter(x=>String(x.status).toUpperCase()==='RECEIVED').length}</strong><small>fully received</small></article><article className="panel"><span>Committed value</span><strong>{currency(ordered.filter(x=>String(x.status).toUpperCase()!=='RECEIVED').reduce((s,x)=>s+safeNumber(x.total),0),settings.currency)}</strong><small>open orders</small></article></section>
  <section className="v5-table-wrap panel"><table><thead><tr><th>PO</th><th>Supplier</th><th>Expected</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>{ordered.map(po=><tr key={po.id}><td><b>{po.poNumber}</b></td><td>{supplierName(po.supplierId)}</td><td>{po.expectedDate||'—'}</td><td><span className="v5-pill">{po.status||'ORDERED'}</span></td><td>{currency(po.total,settings.currency)}</td><td><div className="row-actions"><button onClick={()=>open(po)}>Edit</button>{String(po.status).toUpperCase()!=='RECEIVED'&&<button onClick={()=>openReceive(po)}>Receive</button>}<button className="danger" onClick={async()=>{if(confirm(`Delete ${po.poNumber}?`)){await deleteRecord('purchaseOrders',po.id);notify('Purchase order deleted.');}}}>Delete</button></div></td></tr>)}</tbody></table></section>
  {!ordered.length&&<section className="panel"><EmptyState icon="↧" title="No purchase orders" text="Create a supplier and order inventory."/></section>}
  <Modal open={Boolean(editing)} title={editing?.id?'Edit purchase order':'New purchase order'} onClose={()=>setEditing(null)}><div className="form-grid"><label><span>Supplier</span><select value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Select supplier</option>{suppliers.filter(x=>x.active!==false).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Expected date</span><input type="date" value={form.expectedDate} onChange={e=>setForm({...form,expectedDate:e.target.value})}/></label><label className="wide"><span>Notes</span><textarea rows="2" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="v5-line-editor"><header><h4>Order lines</h4><button className="button button-ghost" onClick={()=>setLines([...lines,newLine()])}>＋ Add line</button></header>{lines.map((line,i)=><div className="v5-line-row" key={i}><select value={line.productId} onChange={e=>{const p=products.find(x=>x.id===e.target.value);updateLine(i,'productId',e.target.value);if(p&&!safeNumber(line.unitCost))updateLine(i,'unitCost',safeNumber(p.cost));}}><option value="">Select item</option>{products.filter(x=>x.trackStock!==false).map(x=><option value={x.id} key={x.id}>{x.name}{x.sku?` · ${x.sku}`:''}</option>)}</select><input type="number" min="0.001" step="0.001" value={line.orderedQty} onChange={e=>updateLine(i,'orderedQty',e.target.value)} title="Quantity"/><input type="number" min="0" step="0.01" value={line.unitCost} onChange={e=>updateLine(i,'unitCost',e.target.value)} title="Unit cost"/><button className="button button-ghost" onClick={()=>setLines(lines.filter((_,index)=>index!==i))}>×</button></div>)}</div><div className="v5-total-strip"><span>Order total</span><strong>{currency(total(lines),settings.currency)}</strong></div><footer className="modal-actions"><button className="button button-ghost" onClick={()=>setEditing(null)}>Cancel</button><button className="button button-primary" onClick={save}>Save purchase order</button></footer></Modal>
  <Modal open={Boolean(receiving)} title={receiving?`Receive ${receiving.poNumber}`:'Receive stock'} onClose={()=>setReceiving(null)}><p className="v5-muted">Enter what physically arrived in this shipment. You can receive the rest later.</p><div className="v5-receive-list">{receipt.map((line,i)=><label key={line.productId}><span>{line.name}</span><input type="number" min="0" step="0.001" value={line.quantity} onChange={e=>setReceipt(receipt.map((x,index)=>index===i?{...x,quantity:e.target.value}:x))}/></label>)}</div><label><span>Receipt note</span><textarea rows="2" value={receiveNote} onChange={e=>setReceiveNote(e.target.value)}/></label><footer className="modal-actions"><button className="button button-ghost" onClick={()=>setReceiving(null)}>Cancel</button><button className="button button-primary" onClick={receive}>Receive stock</button></footer></Modal>
  </div>;
}
