import { useMemo, useState } from 'react';
import Modal from '../components/Modal';
import EmptyState from '../components/EmptyState';
import { deleteRecord, saveRecord } from '../services/database';
import { currency, safeNumber } from '../utils/format';

const blank = { customerId:'', vehicleRegistration:'', vehicleMake:'', vehicleModel:'', mileage:'', complaint:'', diagnosis:'', assignedEmployeeId:'', status:'BOOKED', promisedDate:'', laborEstimate:0, partsEstimate:0, notes:'' };
const STATUSES=['BOOKED','INSPECTION','WAITING PARTS','IN PROGRESS','READY','COMPLETED','CANCELLED'];

export default function ServiceJobs({ jobs = [], customers = [], employees = [], settings = {}, notify = () => {}, onOpenPOS = () => {} }) {
  const [editing,setEditing]=useState(null); const [form,setForm]=useState(blank); const [filter,setFilter]=useState('ACTIVE');
  const visible=useMemo(()=>jobs.filter(job=>filter==='ALL'||(filter==='ACTIVE'?!['COMPLETED','CANCELLED'].includes(String(job.status).toUpperCase()):String(job.status).toUpperCase()===filter)),[jobs,filter]);
  const customer=(id)=>customers.find(x=>x.id===id); const employee=(id)=>employees.find(x=>x.id===id);
  const open=(job=null)=>{setEditing(job||{});setForm({...blank,...(job||{})});};
  const save=async()=>{if(!form.vehicleRegistration.trim())return notify('Vehicle registration is required.','error');const jobNumber=editing?.jobNumber||`JOB-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-4)}`;await saveRecord('serviceJobs',{...form,jobNumber,vehicleRegistration:form.vehicleRegistration.trim().toUpperCase(),laborEstimate:safeNumber(form.laborEstimate),partsEstimate:safeNumber(form.partsEstimate),openedAt:editing?.openedAt||new Date().toISOString()},editing?.id||null);setEditing(null);notify('Service job saved.');};
  const quickStatus=async(job,status)=>{await saveRecord('serviceJobs',{status,[`${status.toLowerCase().replaceAll(' ','')}At`]:new Date().toISOString()},job.id);notify(`${job.jobNumber} → ${status}`);};
  return <div className="v5-page"><section className="v5-hero panel"><div><p className="eyebrow">GARAGE / WORKSHOP</p><h2>Service jobs</h2><p>Manage vehicles, customer complaints, inspections, parts, technicians and work progress.</p></div><div className="v5-action-row"><button className="button button-ghost" onClick={onOpenPOS}>Open Garage POS</button><button className="button button-primary" onClick={()=>open()}>＋ New job</button></div></section>
  <nav className="v5-segmented">{['ACTIVE','ALL',...STATUSES].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</nav>
  <section className="v5-job-grid">{visible.map(job=>{const c=customer(job.customerId);const tech=employee(job.assignedEmployeeId);return <article className="panel v5-job-card" key={job.id}><header><div><p className="eyebrow">{job.jobNumber}</p><h3>{job.vehicleRegistration}</h3><span>{[job.vehicleMake,job.vehicleModel].filter(Boolean).join(' ')||'Vehicle details not set'}</span></div><span className="v5-pill">{job.status}</span></header><div className="v5-detail-list"><span>Customer <b>{c?.name||c?.customerName||'Walk-in'}</b></span><span>Technician <b>{tech?.name||'Unassigned'}</b></span><span>Promised <b>{job.promisedDate||'—'}</b></span><span>Estimate <b>{currency(safeNumber(job.laborEstimate)+safeNumber(job.partsEstimate),settings.currency)}</b></span></div><p className="v5-job-complaint">{job.complaint||'No customer complaint recorded.'}</p><div className="v5-job-progress">{STATUSES.filter(x=>!['CANCELLED'].includes(x)).map(x=><i key={x} className={STATUSES.indexOf(x)<=STATUSES.indexOf(job.status)?'active':''}/>)}</div><footer className="row-actions"><button onClick={()=>open(job)}>Edit</button>{job.status==='BOOKED'&&<button onClick={()=>quickStatus(job,'INSPECTION')}>Inspect</button>}{job.status==='INSPECTION'&&<button onClick={()=>quickStatus(job,'IN PROGRESS')}>Start work</button>}{job.status==='IN PROGRESS'&&<button onClick={()=>quickStatus(job,'READY')}>Ready</button>}{job.status==='READY'&&<button onClick={()=>quickStatus(job,'COMPLETED')}>Complete</button>}<button className="danger" onClick={async()=>{if(confirm(`Delete ${job.jobNumber}?`)){await deleteRecord('serviceJobs',job.id);notify('Service job deleted.');}}}>Delete</button></footer></article>;})}</section>
  {!visible.length&&<section className="panel"><EmptyState icon="⚙" title="No service jobs" text="Create a vehicle work order to start managing garage operations."/></section>}
  <Modal open={Boolean(editing)} title={editing?.id?'Edit service job':'New service job'} onClose={()=>setEditing(null)}><div className="form-grid"><label><span>Customer</span><select value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">Walk-in / no customer</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name||x.customerName}</option>)}</select></label><label><span>Vehicle registration</span><input value={form.vehicleRegistration} onChange={e=>setForm({...form,vehicleRegistration:e.target.value})}/></label><label><span>Make</span><input value={form.vehicleMake} onChange={e=>setForm({...form,vehicleMake:e.target.value})}/></label><label><span>Model</span><input value={form.vehicleModel} onChange={e=>setForm({...form,vehicleModel:e.target.value})}/></label><label><span>Mileage</span><input value={form.mileage} onChange={e=>setForm({...form,mileage:e.target.value})}/></label><label><span>Assigned technician</span><select value={form.assignedEmployeeId} onChange={e=>setForm({...form,assignedEmployeeId:e.target.value})}><option value="">Unassigned</option>{employees.filter(x=>x.active!==false).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Promised date</span><input type="date" value={form.promisedDate} onChange={e=>setForm({...form,promisedDate:e.target.value})}/></label><label><span>Labour estimate</span><input type="number" min="0" step="0.01" value={form.laborEstimate} onChange={e=>setForm({...form,laborEstimate:e.target.value})}/></label><label><span>Parts estimate</span><input type="number" min="0" step="0.01" value={form.partsEstimate} onChange={e=>setForm({...form,partsEstimate:e.target.value})}/></label><label className="wide"><span>Customer complaint / requested work</span><textarea rows="3" value={form.complaint} onChange={e=>setForm({...form,complaint:e.target.value})}/></label><label className="wide"><span>Diagnosis</span><textarea rows="3" value={form.diagnosis} onChange={e=>setForm({...form,diagnosis:e.target.value})}/></label><label className="wide"><span>Notes</span><textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><footer className="modal-actions"><button className="button button-ghost" onClick={()=>setEditing(null)}>Cancel</button><button className="button button-primary" onClick={save}>Save job</button></footer></Modal>
  </div>;
}
