import { useEffect, useState } from 'react';
import { saveBusinessSettings } from '../services/database';
import { OWNER_EMAIL } from '../config/firebase';

export default function Settings({ settings, notify }) {
  const [form, setForm] = useState(settings);
  useEffect(() => setForm(settings), [settings]);
  const save = async () => { await saveBusinessSettings(form); notify('Business settings saved.'); };
  return <section className="settings-layout"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">BUSINESS PROFILE</p><h2>Document and company details</h2></div></div><div className="form-grid settings-form"><label><span>Business name</span><input value={form.businessName || ''} onChange={(e) => setForm({ ...form, businessName: e.target.value })} /></label><label><span>Short name</span><input value={form.shortName || ''} onChange={(e) => setForm({ ...form, shortName: e.target.value })} /></label><label><span>Address</span><input value={form.address || ''} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><label><span>Phone</span><input value={form.phone || ''} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label><span>Email</span><input value={form.email || ''} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label><span>Currency</span><input value={form.currency || ''} onChange={(e) => setForm({ ...form, currency: e.target.value.toUpperCase() })} /></label><label><span>Invoice prefix</span><input value={form.invoicePrefix || ''} onChange={(e) => setForm({ ...form, invoicePrefix: e.target.value.toUpperCase() })} /></label><label><span>Quotation prefix</span><input value={form.quotePrefix || ''} onChange={(e) => setForm({ ...form, quotePrefix: e.target.value.toUpperCase() })} /></label><label className="wide"><span>Google Drive root folder</span><input value={form.driveRootFolder || ''} onChange={(e) => setForm({ ...form, driveRootFolder: e.target.value })} /></label></div><button className="button button-primary" onClick={save}>Save settings</button></article><aside className="panel security-panel"><p className="eyebrow">SECURITY</p><h2>Owner-only access</h2><div className="security-check"><span>✓</span><div><strong>Approved Google account</strong><p>{OWNER_EMAIL}</p></div></div><div className="security-check"><span>✓</span><div><strong>Firestore protected</strong><p>Database requests are checked by Firebase rules.</p></div></div><div className="security-check"><span>✓</span><div><strong>Drive permission is temporary</strong><p>The browser requests a short-lived access token when needed.</p></div></div><p className="security-note">Remember to put the same email in <code>backend/firestore.rules</code>.</p></aside></section>;
}
